apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: barista-gke
  labels:
    app: barista
spec:
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: barista
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
        - name: barista-gke
          image: eu.gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: barista-gke
spec:
  selector:
    app: barista
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer