apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: barista-gke
  labels:
    app: barista
spec:
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: barista
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
        - name: barista-gke
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/firebase-service-account.json"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/firebase-service-account.json
              subPath: firebase-service-account.json
      volumes:
        - name: config-volume
          configMap:
            name: firebase-service-account