apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: "keystore-aux"
  namespace: "default"
data:
  keyPassword: ""
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-config"
  namespace: "default"
data:
  keyAlias: ""
