name: PR validation
on: [pull_request]

jobs:
  setup-build-test:
    name: Setup, Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup and run tests
      run: |-
        touch ./firebase-service-account.json
        echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} > ./firebase-service-account-encoded.json
        base64 -d firebase-service-account-encoded.json > firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS="./firebase-service-account.json"
        export FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        touch ./keystore.p12
        echo ${{ secrets.SSL_KEYSTORE_BASE64 }} > ./keystore.p12.base64
        base64 -d keystore.p12.base64 > keystore.p12
        export SSL_KEYSTORE="./keystore.p12"
        export SSL_KEYSTORE_KEY_ALIAS=${{ secrets.SSL_KEYSTORE_KEY_ALIAS }}
        export SSL_KEYSTORE_PWD=${{ secrets.SSL_KEYSTORE_PWD }}
        ./gradlew test