name: PR validation
on: [pull_request]

jobs:
  setup-build-test:
    name: Setup, Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up secret env vars
      run: |-
        export FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    - name: Build with Gradle
      run: ./gradlew --info build
    - name: Run tests
      run: ./gradlew --info test